name: Build LaTeX document and deploy to GitHub Pages

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: CV.tex
      - name: Move PDF to root
        run: |
          mkdir -p public
          mv CV.pdf public/
          cp index.html public/
      - name: Upload PDF artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy_pages:
    needs: build_latex
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
